# This is a basic workflow to test backupdb.sh to testing.dk-education.com

name: Test backupdb 

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ./dbscripts/backupdb.sh
        host: "198.54.114.130"
        username: "dkedxcwy"
        port: 21098
        privateKey: ${{ secrets.PRIVATE_KEY}}

