# This is a basic workflow to test backupdb.sh to testing.dk-education.com

name: Test backupdb 

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: backup DB via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ./dbscripts/backupdb.sh
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.REMOTE_PORT }}
        privateKey: ${{ secrets.PRIVATE_KEY }}

